### PR TITLE
Issue 3 - Added oauth2 dependency

### PR DESCRIPTION
**Pull request by rodfersou**

### CODE REVIEW

**Comment by rodfersou** [comment]
@hvelarde could you please look at it?

**Comment by hvelarde** [comment]
let me implement CI so the tests are run automatically

**Comment by hvelarde** [comment]
@rodfersou please next time use [z3c.dependencychecker](http://pypi.python.org/pypi/z3c.dependencychecker) so you can add all missing dependencies ;-)

**Comment by rodfersou** [comment]
@hvelarde great! thanks!

**Pull request merged**
